export const ADD_EVENTS = 'ADD_EVENTS';

export const ADD_INFO_GENERALS = 'ADD_INFO_GENERALS';
export const SELECTED_GENERALS = 'SELECTED_GENERALS';

export const ADD_LEGAL_DOCUMENTS = 'ADD_LEGAL_DOCUMENTS';
export const SELECTED_LEGAL_DOCUMENTS = 'SELECTED_LEGAL_DOCUMENTS';
